on:
  push:
    branches:
    - main            
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
          
